# Generated by Django 2.2.2 on 2019-07-13 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_ordertime', models.DateTimeField()),
                ('take_spot', models.CharField(max_length=255)),
                ('banlance', models.IntegerField()),
                ('max_user', models.IntegerField()),
                ('delivery_price', models.BooleanField(default=0)),
                ('status', models.CharField(choices=[('P', 'PROCEEDING'), ('C', 'CONFIRM'), ('F', 'FINESHED')], default='P', max_length=1)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField()),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Matching')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('min_price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('brandImage', models.ImageField(upload_to='media/restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('matchingParticipant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MatchingParticipant')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('foodImage', models.ImageField(upload_to='media/menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='matching',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Restaurant'),
        ),
    ]
