# Generated by Django 2.2.2 on 2019-06-16 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.IntegerField(blank=True, choices=[(0, '기숙사'), (1, '궁동'), (2, '죽동')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
