# Generated by Django 2.2.3 on 2019-08-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_restaurant_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='delivery_price',
        ),
    ]
